create checkbox
js-tasks-ru/htmlcss-20241107_gergil-v pull request #13
Opened 2024-12-13 08:08 UTC by gergVlad

2024-12-13 08:08 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-16 18:41 UTC, GSemikozov requested changes

2024-12-16 18:41 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.wrapper {
это не часть блока, вспомогательные обертки создавать можно, но вне файла стилей блока

2024-12-22 10:48 UTC, GSemikozov approved these changes

2024-12-22 10:48 UTC, merged