create toggler
js-tasks-ru/htmlcss-20241107_gergil-v pull request #15
Opened 2024-12-13 10:32 UTC by gergVlad

2024-12-13 10:33 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-16 18:43 UTC, GSemikozov requested changes

2024-12-16 18:43 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.wrapper {
см коммент по чекбоксу

2024-12-22 10:49 UTC, GSemikozov requested changes
конфликт

2025-01-09 09:55 UTC, GSemikozov approved these changes

2025-01-09 09:55 UTC, merged