09 burger menu
js-tasks-ru/htmlcss-20241107_gergil-v pull request #17
Opened 2024-12-13 14:02 UTC by gergVlad

2024-12-13 14:02 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-16 05:16 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-16 05:19 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-16 18:48 UTC, GSemikozov requested changes

2024-12-16 18:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.header__top {
здесь верстаем бургер-меню, не должно быть других классов блоков или элементов

2024-12-16 18:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-button {
это не часть блока

2024-12-16 18:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    position: absolute;
fixed

2024-12-16 18:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    background: url("img/close.svg") no-repeat;
через фон не надо

2024-12-16 18:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                <div class="header__logo"><img src="img/logo.png" alt="логотип"></div>
свг через img не надо, иначе потеряем векторность

2024-12-20 10:38 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-20 10:42 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-20 10:48 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-09 08:00 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-09 09:59 UTC, GSemikozov requested changes
нужно исправить конфликт

2025-01-09 09:59 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    max-width: 350px;
мне кажется на уровне блока нет смысла в этом ограничении)

2025-01-09 09:59 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    margin-bottom: 11px;
5

2025-01-09 09:59 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__icon_success .path {
ой.. нужно сделать так, чтобы можно было менять цвет иконки задавая color

2025-01-09 09:59 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_invalid input {
.input_invalid .input__field?

2025-01-09 09:59 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-button {
бургер меню в этом ПР-е лишний?

2025-01-09 10:07 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2025-01-09 10:20 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-09 10:54 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-11 09:05 UTC, GSemikozov requested changes

2025-01-11 09:05 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.icon {
.burger-menu__icon

2025-01-11 09:25 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2025-01-11 16:04 UTC, GSemikozov approved these changes

2025-01-11 16:04 UTC, merged