create tooltip
js-tasks-ru/htmlcss-20241107_gergil-v pull request #7
Opened 2024-12-08 08:27 UTC by gergVlad

2024-12-08 08:27 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-12 14:14 UTC, GSemikozov requested changes

2024-12-12 14:14 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
глобальные стили в файлах стилей компонентов не пишем

2024-12-12 14:14 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: auto;
лишнее

2024-12-15 10:51 UTC, GSemikozov requested changes

2024-12-15 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 300px auto;
марджины на уровне блока не задаем

2024-12-15 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    width: 24px;
ширина и высота зависит от триггера

2024-12-16 18:25 UTC, GSemikozov requested changes

2024-12-16 18:25 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_margin {
но ведь это все равно задает марджины блоку ))
надо удалить. Если хочется увидеть тултип в рамках тестовой страницы - можно на body инлайном задать паддинги сверху 300px

2024-12-22 10:47 UTC, GSemikozov approved these changes

2024-12-22 10:47 UTC, merged