create popup
js-tasks-ru/htmlcss-20241107_gergil-v pull request #8
Opened 2024-12-09 07:49 UTC by gergVlad

2024-12-09 07:49 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-12 14:15 UTC, GSemikozov requested changes

2024-12-12 14:15 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.popup-button {
не нужно создавать отдельную кнопку для открытия модалки + это не элемент данного блока

2024-12-12 14:15 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
fixed

2024-12-15 10:51 UTC, GSemikozov approved these changes

2024-12-15 10:52 UTC, merged